<?php

namespace Container7vxR8pM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUsersControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\UsersController' shared autowired service.
     *
     * @return \App\Controller\UsersController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/UsersController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/ServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Service/UserService.php';

        return $container->services['App\\Controller\\UsersController'] = new \App\Controller\UsersController(new \App\Service\UserService(($container->privates['App\\Repository\\UsersRepository'] ?? $container->load('getUsersRepositoryService'))), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
