version: "3"

services:
  nginx:
    container_name: novex-nginx
    image: nginx
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    ports:
      - "80:80"
    restart: always
    depends_on:
      - php
      - db

  php:
    container_name: novex-php
    build: ./docker/php
    restart: always
    volumes:
      - ./:/var/www/html

  composer:
    container_name: novex-composer
    image: composer
    volumes:
      - ./:/app
    command: install

  db:
    container_name: novex-db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"