<?php

namespace Container6Ccx6Gu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Controller' shared autowired service.
     *
     * @return \App\Controller\Controller
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/Controller.php';

        return $container->services['App\\Controller\\Controller'] = new \App\Controller\Controller();
    }
}
